### ISSUE TITLE
Body tracking does not work well

### ISSUE THREAD

**Issue by sicheong** [microsoft/Azure-Kinect-Sensor-SDK#1356] opened 2020-09-17 02:10 UTC
**Describe the bug**
When a leg is raised high, body tracking SDK can't recognize that leg.
I think it happens when a foot rises above the waist.

**Screenshots**
![ScreenCapture 01](https://user-images.githubusercontent.com/71307173/93411324-df855080-f8d5-11ea-95f1-0194658d0f3d.png)

**Desktop (please complete the following information):**
 - OS with Version: Windows 1903
 - SDK Version:  1.0.1
 - Firmware version:  1.6.110079014

**Comment by qm13** [comment] 2020-09-17 21:08
Thus is a known issue. See #738.

**Comment by billpottle** [comment] 2020-11-12 15:45
@sicheong - We investigated this issue in detail, and found that it's actually prevalent across a number of models - ie, similar issues happen with OpenPose as well. The general consensus was that we would have to train our own model with thousands of data points to include kicks at high speed.

**Comment by qm13** [comment] 2020-11-30 22:39
@billpottle you are correct. Whilst we did capture a bunch of data of people exercising we did not specifically capture data for high kicks. We are currently researching ways for developers to customize the model (a core reason we opted to move to DNN from random forest). Nothing to announce yet.

**Comment by qm13** [comment] 2021-03-24 01:49
Duplicate of #738.

**Closed as completed by qm13** 2021-03-24 01:49 UTC
Labels: Bug, Body Tracking
