### ISSUE TITLE
ssh failed to start device

### ISSUE THREAD

**Issue by Crazysiri** [microsoft/Azure-Kinect-Sensor-SDK#1328] opened 2020-08-21 10:44 UTC
the same executable file such as 'streaming_sampes'

it is correct run from local but error occurs when run from ssh :

[2020-08-21 18:32:13.963] [error] [t=19986] ../src/dewrapper/dewrapper.c (154): depth_engine_start_helper(). Depth engine create and initialize failed with error code: 204.
[2020-08-21 18:32:13.963] [error] [t=19986] ../src/dewrapper/dewrapper.c (160): deresult == K4A_DEPTH_ENGINE_RESULT_SUCCEEDED returned failure in depth_engine_start_helper()
[2020-08-21 18:32:13.963] [error] [t=19986] ../src/dewrapper/dewrapper.c (194): depth_engine_start_helper(dewrapper, dewrapper->fps, dewrapper->depth_mode, &depth_engine_max_compute_time_ms, &depth_engine_output_buffer_size) returned failure in depth_engine_thread()
[2020-08-21 18:32:13.965] [error] [t=19974] ../src/dewrapper/dewrapper.c (552): dewrapper_start(). Depth Engine thread failed to start
[2020-08-21 18:32:13.965] [error] [t=19974] ../src/depth/depth.c (398): dewrapper_start(depth->dewrapper, config, depth->calibration_memory, depth->calibration_memory_size) returned failure in depth_start()
[2020-08-21 18:32:13.965] [error] [t=19974] ../src/depth_mcu/depth_mcu.c (359): cmd_status == CMD_STATUS_PASS returned failure in depthmcu_depth_stop_streaming()
[2020-08-21 18:32:13.965] [error] [t=19974] ../src/depth_mcu/depth_mcu.c (362): depthmcu_depth_stop_streaming(). ERROR: cmd_status=0x00000063
[2020-08-21 18:32:13.965] [error] [t=19974] ../src/sdk/k4a.c (895): depth_start(device->depth, config) returned failure in k4a_device_start_cameras()
Failed to start device

**Comment by Crazysiri** [comment] 2020-08-21 10:58
I've seen a solution from other issue, run command like this: 'DISPLAY=:0 ./xx'
but how to add 'DISPLAY=:0' to Clion (code editor)

**Comment by qm13** [comment] 2020-08-24 17:49
This is a duplicate of a known issue #810

**Closed as completed** 2020-08-29 00:38 UTC
Labels: Bug, Duplicate
