### ISSUE TITLE
Skeleton smoothing is too aggressive for low FPS

### ISSUE THREAD

**Issue by bibigone** [microsoft/Azure-Kinect-Sensor-SDK#521] opened 2019-07-21 18:19 UTC
It looks like that Body Tracking SDK applies some kind of smoothing to skeletal tracking results. And this smoothing is too aggressive, especially for frame rates lower than 30 FPS (15 FPS, not mentioning 5 FPS). This results in significant inaccuracy: skeleton is behind real pose in terms of frame-to-frame movement:
![nfov_2x2binned_15fps_smoothing](https://user-images.githubusercontent.com/3883639/61595226-307bb500-abfd-11e9-9104-a14ed1682a5a.png)

Is it possible to add some setting for this smoothing?

**Comment by Brekel** [comment] 2019-07-21 18:29
I noticed the same thing and fully agree, it seems it's even over smoothing at 30 fps. (I didn't try 15/5 fps actually)
Here's a (quite popular) feedback ticket I filed a little while ago that you can up-vote: https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/38027029-user-adjustable-skeleton-smoothing

**Comment by tesych** [comment] 2019-07-22 17:12
duplicate of #514

**Closed by tesych** 2019-07-22 17:12 UTC
Labels: Body Tracking, Bug, Duplicate
