### ISSUE TITLE
Cuda 10.1 support

### ISSUE THREAD

**Issue by derivativerobmc** [microsoft/Azure-Kinect-Sensor-SDK#1125] opened 2020-03-11 20:38 UTC
Is there a timeline for updating the library to Cuda 10.1? We're switching over to Visual Studio 2019 and my understanding is that cuda 10.0 has problems with visual studio 2019.

**Comment by yijiew** [comment] 2020-03-16 23:32
All our development and sample code projects are using VS2019 and we didn't see any problem. Could you clarify what kind of issue you will hit by using Cuda 10.0 dll in VS2019?

**Comment by derivativerobmc** [comment] 2020-03-17 22:52
host_config.h in the Cuda 10.0.130 SDK has a line that checks for the MSC_VER and currently throws an error if it's greater than or equal to 1920 with the message that only VS 2013 - 2017 are supported

**Comment by yijiew** [comment] 2020-03-18 15:29
Thanks for clarification. But for the body tracking SDK, only the cuda binaries are needed. Customers shouldn't need to link to Cuda SDK at all.

**Comment by derivativerobmc** [comment] 2020-03-18 17:14
We're not using it for the body tracking, but we do use the Cuda SDK a lot in other parts of our project. We've disabled it for the moment to get things working, but we'll need it in the long run.

I noticed the onnxruntime 1.2 says it upgraded to cuda 10.1 about a week ago. Will this get carried over to the kinect relatively soon?

thanks for the help.

**Comment by derivativerobmc** [comment] 2020-06-09 23:13
Any word on updating the body tracking sdk to use a newer version of cuda? Other components in our project require 10.1 and we don't want to be shipping multiple versions.

**Comment by maruta** [comment] 2020-10-06 00:16
I'm experiencing a problem with k4abt_simple_3d_viewer.exe on a Windows machine with RTX 3080, where the tracking window doesn't appear and not even a log file is generated.

I'm beginning to suspect that a lower version of the bundled CUDA is the cause, as it works when I remove the RTX 3080 and install a much older GT710, and it works even with the CPU options specified.

For your information, the same binary works correctly on another Windows machine with Quadro RTX 5000 (Turing architecture).

So far, I'm not sure if that's a reason to upgrade the CUDA version or if it's a problem with my RTX3080 unit, I'm writing here in the hopes that someone else experiencing the same phenomenon will find it.

**Comment by qm13** [comment] 2020-10-06 21:06
We have had several reports of issues with the RTX 3080. The issue is likely with CUDA version which is an ONNX Runtime dependency. We are working with the ONNX team to make sure this is addressed in the next release of the Body Tracking SDK which is targeted for end of October / early November.

**Comment by chrisnovello** [comment] 2020-10-28 09:40
+1 having the same problem with k4abt_simple_3d_viewer.exe as @maruta, also on rtx 30 series, also had same binary working on a different machine & gpu. runs (very slowly) on this current machine if I execute with the CPU only mode

additionally, seeing a freeze upon trying to init the unit with an Unreal plugin that uses the sdk, which might be related (same plugin was also working on other machine)

eager for new release and to see if 30 series helps give a boost to skeleton tracking

**Comment by datee** [comment] 2020-11-17 08:41
Can confirm this issue also, on a computer with RTX 3090 the k4abt_simple_3d_viewer does not open the tracking window. 
It just stops. No crash but just nothing happening. CPU mode works fine.

When compiling and testing the examples **(simple_cpp_sample)** ..its the same.. stops at this line : 
` k4abt::tracker tracker = k4abt::tracker::create(sensor_calibration);`

Really need this, hope a fix is on the way! :)

**Comment by L4Z3RC47** [comment] 2020-11-17 18:11
> 
> 
> Can confirm this issue also, on a computer with RTX 3090 the k4abt_simple_3d_viewer does not open the tracking window.
> It just stops. No crash but just nothing happening. CPU mode works fine.
> 
> When compiling and testing the examples **(simple_cpp_sample)** ..its the same.. stops at this line :
> ` k4abt::tracker tracker = k4abt::tracker::create(sensor_calibration);`
> 
> Really need this, hope a fix is on the way! :)

Confirmed here as well. RTX 3090. 

@yijiew or @qm13 any updates on ETA for the next release?

**Comment by VegetableWithChicken** [comment] 2020-11-29 10:23
Who can tell me, has this problem been solved and what needs to be updated. I updated to cudn10.1, but it has no effect.
Do I need to move the CUDN DLL library to bianary replacement of body tracking file ？？
#1423

**Comment by RoseFlunder** [comment] 2020-11-29 12:22
I think Microsoft needs to release a new Version thats compiled with a Onxx runtime that uses cuda 11.
I think we as users can just wait.
Is that right?

**Comment by qm13** [comment] 2020-11-30 21:55
Currently investigating issue.

**Comment by L4Z3RC47** [comment] 2020-12-13 23:33
> 
> 
> We have had several reports of issues with the RTX 3080. The issue is likely with CUDA version which is an ONNX Runtime dependency. We are working with the ONNX team to make sure this is addressed in the next release of the Body Tracking SDK which is targeted for end of October / early November.

@qm13 is there a new target date for the next release?

**Comment by damaza** [comment] 2020-12-25 01:22
> I'm experiencing a problem with k4abt_simple_3d_viewer.exe on a Windows machine with RTX 3080, where the tracking window doesn't appear and not even a log file is generated.
> 
> I'm beginning to suspect that a lower version of the bundled CUDA is the cause, as it works when I remove the RTX 3080 and install a much older GT710, and it works even with the CPU options specified.
> 
> For your information, the same binary works correctly on another Windows machine with Quadro RTX 5000 (Turing architecture).
> 
> So far, I'm not sure if that's a reason to upgrade the CUDA version or if it's a problem with my RTX3080 unit, I'm writing here in the hopes that someone else experiencing the same phenomenon will find it.

The same problem with RTX3070

**Comment by L4Z3RC47** [comment] 2020-12-25 01:55
All 3000 series cards are affected. Hoping we can get an ETA soon. I have commercial applications that could really use this!!!

**Comment by VegetableWithChicken** [comment] 2020-12-28 03:32
> Currently investigating issue.

  i am also very worried. Please ,please tell me the completion data !
3Q

**Comment by jenyaone** [comment] 2020-12-30 16:22
> Currently investigating issue.

are there any updates on this? please let us know.

**Comment by Lt23live** [comment] 2021-01-05 03:50
We are also having this issue, RTX 3080 series. Microsoft needs to address this.

**Comment by L4Z3RC47** [comment] 2021-01-05 04:04
ping @qm13

**Comment by Lt23live** [comment] 2021-01-07 18:27
@qm13  has there been any updates?

**Comment by AquaLamp** [comment] 2021-01-10 02:21
Thank you. I am eagerly awaiting the results of your investigating issue.

**Comment by damaza** [comment] 2021-01-11 01:08
@qm13

**Comment by L4Z3RC47** [comment] 2021-01-12 16:06
@qm13 any news? This ticket seems to revolve around onnxruntime support of CUDA 10.1 however onnxruntime has supported both cuda 10.2 and cuda 11 since release 1.5.1 
I assume that this is more than just a simple runtime issue then but given this is a major blocker on current gen hardware it would be great to get some deeper feedback on what the issue investigation has revealed and what/if there is a timeline for an update. 
Thank you!

**Comment by UnaNancyOwen** [comment] 2021-01-19 04:21
@qm13 Currently, the market is moving to GeForce 30XX generation products, and GeForce 20XX/10XX generation products have come to end of sales. NVIDIA has announced the 30XX generation products for laptops. All desktop/laptop on the market will soon be replaced by 30XX generation GPU.
This is a very serious problem for businesses. In fact, we are having trouble procuring new PC that deliver to our customers for work. Please, hurry up with this task (update ONNX Runtime to CUDA 11.x, or support [DirectML provider](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1343)). Thanks!

**Comment by L4Z3RC47** [comment] 2021-01-20 02:56
> @qm13 Currently, the market is moving to GeForce 30XX generation products, and GeForce 20XX/10XX generation products have come to end of sales. NVIDIA has announced the 30XX generation products for laptops. All desktop/laptop on the market will soon be replaced by 30XX generation GPU.
> This is a very serious problem for businesses. In fact, we are having trouble procuring new PC that deliver to our customers for work. Please, hurry up with this task (update ONNX Runtime to CUDA 11.x, or support [DirectML provider](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1343)). Thanks!

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1481#issuecomment-763288112

Per @qm13 looks like we should see an update around mid next month (usual caveats apply)

great news!

**Comment by jaymimc** [comment] 2021-03-17 03:35
> We have had several reports of issues with the RTX 3080. The issue is likely with CUDA version which is an ONNX Runtime dependency. We are working with the ONNX team to make sure this is addressed in the next release of the Body Tracking SDK which is targeted for end of October / early November.

Sorry, know i have also listed this on another ticket but it suggested it was closed. As this is still an open ticket, is there any update on when SDK, CUDA and Body Tracking working with NVIDIA 3xxx cards?

**Comment by qm13** [comment] 2021-03-19 19:48
Upgraded to CUDA 11.1

**Closed by qm13** 2021-03-19 19:48 UTC
Labels: Body Tracking, Enhancement, Triage Approved

**Comment by AswinkarthikeyenAK** [comment] 2021-03-30 11:43
Hi Guys,
Can anyone confirm if the body tracking is working fine without any issues with the RTX30xx graphic card,please?
I am planning to buy a desktop with the RTX3070 and I wanted check before I could purchase the desktop. 
Thanks for your feedback !!

**Comment by lewkoo** [comment] 2021-03-30 12:00
I can confirm that it works fine on RTX 3070 whereas before it didn't. This is on bare-metal Ubuntu 18.04. 
See screenshot below as proof. 
![k4abt_rtx_3070](https://user-images.githubusercontent.com/2424251/112985179-8772b500-9168-11eb-80fc-11bdb7c41f96.png)

**Comment by AswinkarthikeyenAK** [comment] 2021-03-30 12:36
Hi @lewkoo,
Thanks for the information

**Comment by AhmedMedhat** [comment] 2021-04-18 05:22
After upgrading the body tracking library to v1.1, the `k4abt_simple_3d_viewer` example runs on RTX 3090 (CUDA Version: 11.2), however it prints the following message before creating the tracking window:
``` 
2021-04-17 21:15:30.444827715 [W:onnxruntime:K4ABT_ORT_Environment, cuda_execution_provider.cc:1885 GetCapability] CUDA kernel not found in registries for Op type: Sign node name: Sign
2021-04-17 21:15:30.446831171 [W:onnxruntime:K4ABT_ORT_Environment, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: Shape__40
```
@qm13  What does this message mean? Does it fallback to CPU processing? @lewkoo did you get similar message when running on RTX 3070?
Thanks for the efforts,

**Comment by lewkoo** [comment] 2021-04-20 14:24
> After upgrading the body tracking library to v1.1, the `k4abt_simple_3d_viewer` example runs on RTX 3090 (CUDA Version: 11.2), however it prints the following message before creating the tracking window:
> 
> ```
> 2021-04-17 21:15:30.444827715 [W:onnxruntime:K4ABT_ORT_Environment, cuda_execution_provider.cc:1885 GetCapability] CUDA kernel not found in registries for Op type: Sign node name: Sign
> 2021-04-17 21:15:30.446831171 [W:onnxruntime:K4ABT_ORT_Environment, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: Shape__40
> ```
> 
> @qm13 What does this message mean? Does it fallback to CPU processing? @lewkoo did you get similar message when running on RTX 3070?
> Thanks for the efforts,

I got identical message when running `k4abt_simple_3d_viewer` on 18.04 Ubuntu with CUDA 11.2. Possibly due to [this](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1481#issuecomment-803077212).

AFAIK, it doesn't fallback to CPU processing, at least not entirely. `nvidia-smi` still shows a process and GPU is experiencing some additional load. From the error message, I can wild guess that it is off loading body shape detection to CPU, while everything else is still running on GPU but this is just a guess. However, our applications that use body tracking seem to perform just as they used to despite these error messages.

**Comment by qm13** [comment] 2021-04-26 22:24
@lewkoo That warning is expected. Please see the troubleshooting notes for AKDK in the documentation.

**Comment by LU-MING-HUA** [comment] 2021-10-20 10:44
I have a question. I use Win10P RTX3080 to turn on body tracking v1.1.0 but it can’t be displayed. I use CUDA 11.1 according to the article. Is anyone like me? I am a student  first contact with Azure Kinect

**Comment by ZodiacWind** [comment] 2021-12-09 11:03
> I have a question. I use Win10P RTX3080 to turn on body tracking v1.1.0 but it can’t be displayed. I use CUDA 11.1 according to the article. Is anyone like me? I am a student first contact with Azure Kinect

I have encountered the same issue. Could anybody provide some instructions? Really appreciate it.

**Comment by VegetableWithChicken** [comment] 2021-12-09 11:04
您好，我一般不常用邮箱，有重要邮件，请QQ我下，谢谢!

**Comment by stroombeestje** [comment] 2022-02-19 18:22
> > I have a question. I use Win10P RTX3080 to turn on body tracking v1.1.0 but it can’t be displayed. I use CUDA 11.1 according to the article. Is anyone like me? I am a student first contact with Azure Kinect
> 
> I have encountered the same issue. Could anybody provide some instructions? Really appreciate it.

Same issue here on a 3090RTX

**Comment by tinywolf3** [comment] 2023-06-11 20:01
same here. please fix it.
