### ISSUE TITLE
why  there is a   poor performance of the DirectML/CPU  with body track v1.1.0 ?

### ISSUE THREAD

**Issue by senshin998** [microsoft/Azure-Kinect-Sensor-SDK#1613] opened 2021-05-30 01:43 UTC
Its current performance results in high lag and overconsumption of CPU even if you have a powerful graphics card or a powerful 
 cpu, I was even optimistic about  body track v1.0.1 .what  difference between  v1.0.1 and  v1.1.0? 

![QQ图片20210530094103](https://user-images.githubusercontent.com/17866598/120089290-4af11480-c12b-11eb-8de0-16ddcd3bba14.png)

**Comment by qm13** [comment] 2021-08-16 18:49
Duplicate of #1546

**Closed as completed by qm13** 2021-08-16 18:49 UTC
Labels: Bug, Body Tracking
