### ISSUE TITLE
Is there any way to assign device ID for the basic level of GPU use ? not by setting "tracker_config.gpu_device_id" ,It's  only for body tracker .

### ISSUE THREAD

**Issue by senshin998** [microsoft/Azure-Kinect-Sensor-SDK#1629] opened 2021-06-25 04:29 UTC

**Comment by diablodale** [comment] 2021-06-25 18:34
duplicate of https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1428

**Closed as completed** 2021-08-16 17:53 UTC
Labels: Bug
