### ISSUE TITLE
USB-xHCI Driver from Microsoft doesn't work for Azure Kinect

### ISSUE THREAD

**Issue by Zailux** [microsoft/Azure-Kinect-Sensor-SDK#1440] opened 2020-12-11 10:27 UTC
**Describe the bug**
I am aware that there are only specific host controller driver working for the Azure Kinect (https://docs.microsoft.com/en-us/azure/Kinect-dk/troubleshooting#usb3-host-controller-compatibility). My desktop ootb uses the ASMedia 3.0 extensible hostcontroller which is already reported not working for the Azure Kinect. Therefore I changed to the Microsoft USB-xHCI-compatible hostcontroller from Microsoft, but the device doesn't start. 

I just need the hint which exact driver i need to get the Azure Kinect running. A download link or the like would be great.
There was no Intel USB 3.0 Host Controller available in the driver list. As far as I googled Intel doesn't even support USB 3.0 Hostcontroller atm.

**To Reproduce**
1. Plugin the Azure Kinect to USB 3.0 Port and start the desktop
2. Check in device manager the USB Port.
3. Change the driver to the Microsoft USB Driver (details see below)
4. Check whether the device is correctly started. 

**Desktop (please complete the following information):**
 - Processor: Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz   2.50 GHz
 - OS with Version: Windows 10 Pro - 19042.685
 - SDK Version:  1.4.1
 - Firmware version:  AzureKinectDK_Fw_1.6.110079014  (checked the version on my notebook). 
 - Port: INtel(R) C600/X/) series chipset PCI Express Root Port 5 - 1d18
 - Available Drivers: 
Microsoft Gerneic USB xHCI Hostcontroller - USBXHCI.SYS  - Version W10.0.19041.662
ASMedia USB 3.0 extensible hostcontroller - 0.96  - version 10.0.19041.662
 - Mainboard: ASUSTek COMPUTER - P9X79 WS  - Chipsets Intel X Sandry Bride-E | Intel X79

Thanks ! :)

**Comment by qm13** [comment] 2020-12-14 18:20
The Intel USB Controller driver is included with Windows. You are using an Intel motherboard. Are none of your USB ports backed by an Intel USB controller (integrated with the CPU)?

**Comment by Zailux** [comment] 2020-12-14 20:25
The Intel USB driver are unfortunately only for the USB 2.0 ports. The USB 3.0 drivers are from ASMedia or the other one mentioned above. I have two USB 3.0 Ports which don't have the appropriate 3.0 driver. Can you give me hint where I should find the driver in the device manager menu, or rather the install driver menu ? Better would be a link where I could download the necessary driver, but I guess you guys don't have one directly available. 

Do you need any more specific information, can I provide anything else?

The only driver I found online, are not applicable for my chipset (https://downloadcenter.intel.com/download/22824/Intel-USB-3-0-eXtensible-Host-Controller-Driver-for-Intel-8-9-100-Series-and-Intel-C220-C610-Chipset-Family)

**Comment by qm13** [comment] 2021-01-08 20:43
There is a known issue with ASMedia USB chip sets on Windows. We currently do not have a fix.

**Comment by qm13** [comment] 2021-01-08 21:54
Duplicate of #1409

**Closed as completed** 2021-02-22 19:31 UTC
Labels: Bug, Duplicate
