### ISSUE TITLE
When can we expect body tracking on ARM64?

### ISSUE THREAD

**Issue by anselanza** [microsoft/Azure-Kinect-Sensor-SDK#1342] opened 2020-09-04 12:39 UTC
> This version (1.4.0) does not support body tracking sdk on Ubuntu 18.04.
> Is there any way to deal with this?

Body Tracking team is also adding ARM support. A new version of BT is coming that will work with 1.4.0.

_Originally posted by @wes-b in https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1093#issuecomment-611617173_

**Comment by anselanza** [comment] 2020-09-04 12:41
Just wondering if there has been any update since this last comment on the issue (that I can find), which was back in April.

Completely appreciate that these things take time, but just wondering if there is an ETA?

I have depth/RGB camera input working perfectly on Nvidia Jetson Xavier NX, but of course body tracking is still officially not supported yet for this platform.

**Comment by qm13** [comment] 2020-09-10 20:54
This is still under development.

**Comment by anselanza** [comment] 2020-09-23 09:50
Yes, understood that it is still in development, but was curious if there was any rough timeline? I don't want to put pressure on developers, but since the last update was 5 months ago, I was wondering if it was something coming soon (in the next month) or still half a year away?

**Comment by sbr-dev** [comment] 2020-09-30 14:30
@qm13 Hi !
Could you please give some information about BodyTracking linux support as well ? I need to know if the release might happen soon or not so we can device if w need to create something ourself for body tracking support on linux platform

**Comment by anselanza** [comment] 2020-10-01 08:20
> Could you please give some information about BodyTracking linux support as well ? I need to know if the release might happen soon or not so we can device if w need to create something ourself for body tracking support on linux platform

As far as I know, Body Tracking works just fine on Linux! See https://docs.microsoft.com/en-us/azure/kinect-dk/body-sdk-download#linux-installation-instructions

But currently it only works for x64 architecture. Whereas I would like to try running this on a Jetson Xavier, which uses ARM64.

**Comment by thinkinginmath** [comment] 2020-12-30 19:41
@qm13 
Any update on timeline of the body-tracking on ARM? 
Is there anything the open source developers can help on the porting efforts? 

https://developer.nvidia.com/blog/announcing-onnx-runtime-for-jetson/

**Comment by flugi** [comment] 2021-02-26 12:33
Any news on ARM64 support for Body Tracking? I have read somewhere an estimation that Xavier NX will be capable, is there any information about this regard?

**Comment by cjangrist** [comment] 2021-03-12 05:25
+1 for status update. Is this something perhaps the community could help contribute? If so do you have any pointers on how to go about doing this for folks staring out?

Hoping to get body tracking working on nvidia xavier

**Comment by cjangrist** [comment] 2021-04-21 17:29
Any news on ARM64 support for Body Tracking?

**Comment by qm13** [comment] 2021-07-08 18:01
Unfortunately we have encountered some sever issues getting body tracking running performantly on ARM64.

**Comment by tank104** [comment] 2021-07-08 20:52
@qm13 does that mean you are pausing it, or just working through the issues, and will release soon?

**Comment by burakaksoy** [comment] 2021-11-04 18:17
Still hopefully waiting for the support..

**Comment by qm13** [comment] 2022-05-17 01:04
Duplicate of #871.

**Closed as completed by qm13** 2022-05-17 01:04 UTC
Labels: Body Tracking, Ask a Question
