### ISSUE TITLE
Body Tracking Viewer crash on startup

### ISSUE THREAD

**Issue by leGITplease** [microsoft/Azure-Kinect-Sensor-SDK#1696] opened 2021-10-27 17:33 UTC
Hi guys, im new here and a student, if i do anything wrong pls be nice, im doing my best.

PC:
AMD Ryzen 5 2600 Six-Core Processor               3.40 GHz
x64
Gigabyte GeForce GTX 1660 OC 6G
16GB RAM
Windows 10 Pro

The following versions i have installed:

NVIDIA driver (latest): 
![driverUptoDate](https://user-images.githubusercontent.com/13260266/139115028-5551c787-7376-442d-be7d-c59e167a115a.PNG)

Nvidia CUDA 11.5:
![cudaScreen](https://user-images.githubusercontent.com/13260266/139115921-16d35781-d515-4a4b-83d0-33cff48665ed.PNG)

The CUDA installer shows the following message:
     - Nsight Monitor
**Not Installed:**
     **- Nsight for Visual Studio 2019
       Reason: VS2019 was not found
     - Nsight for Visual Studio 2017
       Reason: VS2017 was not found
     - Integrated Graphics Frame Debugger and Profiler
       Reason: see https://developer.nvidia.com/nsight-vstools
     - Integrated CUDA Profilers
       Reason: see https://developer.nvidia.com/nsight-vstools**
**<- would that be a problem?**

Azure Kinect SDK 1.4.1
Firmware: 1.6.1110079014
![windowsFirmwareKinectSDKVersions](https://user-images.githubusercontent.com/13260266/139113926-8b99491a-7cbf-4cfd-826c-a313d962cd47.png)

I have searched existing issues:

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1092
This article says its after 2 mins, but mine crashes instantly.

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1242
i have updated to the latest firmware version:
![windowsFirmwareKinectSDKVersions](https://user-images.githubusercontent.com/13260266/139117193-4708ce75-5a14-46e5-a285-17a276c310be.png)

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1625
i have installed the c++ distribution noted in the documentation found here:
https://www.microsoft.com/en-us/download/details.aspx?id=48145
version 2015 x64 - of which x64 is the same as my pc

-->

**Describe the bug**
Crash on startup of the Azure Body tracking Viewer, no error log available:
![screenshot command prompt kinect updaten installen etc]
![azureKinectCrashOnStartup](https://user-images.githubusercontent.com/13260266/139117073-ee334ba4-0240-44f8-90b3-853bd03e039a.png)

The Viewer does seem to work perfectly, no issues i have detected:
![k4aviewer screenshot](https://user-images.githubusercontent.com/13260266/139115235-64cfa416-0392-4cb2-9ec3-41efb8ee1701.png)

**To Reproduce**
Open on Azure Body tracking Viewer.

I also tried to use the description in the manual but there is no change of behaviour on startup:

"Launch the Azure Kinect Body Tracking Viewer to check that the Body Tracking SDK is set up correctly. The viewer is installed with the SDK msi installer. You can find it at your start menu or at <SDK Installation Path>\tools\k4abt_simple_3d_viewer.exe.
**If you don't have a powerful enough GPU and still want to test the result, you can launch the the Azure Kinect Body Tracking Viewer in the command line by the following command: <SDK Installation Path>\tools\k4abt_simple_3d_viewer.exe CPU**
If everything is set up correctly, a window with a 3D point cloud and tracked bodies should appear."

I also tried to do all the steps to get here again but i keep having the same result :/

Help is welcome, thanks.

**Comment by ytrock** [comment] 2021-10-28 09:40
same problem. 
And if I try to launch the body tracker using C++ code, it outputs: 

2021-10-28 17:29:19.3643539 [W:onnxruntime:K4ABT_ORT_Environment, cuda_execution_provider.cc:1885 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not found in registries for Op type: Sign node name: Sign
2021-10-28 17:29:19.3686044 [W:onnxruntime:K4ABT_ORT_Environment, fallback_cpu_capability.h:140 onnxruntime::GetCpuPreferedNodes] Force fallback to CPU execution for node: Shape_2__37
2021-10-28 17:29:19.3686875 [W:onnxruntime:K4ABT_ORT_Environment, fallback_cpu_capability.h:140 onnxruntime::GetCpuPreferedNodes] Force fallback to CPU execution for node: lambda_5/Shape__90
2021-10-28 17:29:19.3687516 [W:onnxruntime:K4ABT_ORT_Environment, fallback_cpu_capability.h:140 onnxruntime::GetCpuPreferedNodes] Force fallback to CPU execution for node: lambda_5/mul_1
2021-10-28 17:29:19.3687903 [W:onnxruntime:K4ABT_ORT_Environment, fallback_cpu_capability.h:140 onnxruntime::GetCpuPreferedNodes] Force fallback to CPU execution for node: lambda_5/Reshape__92

**Comment by leGITplease** [comment] 2021-10-28 09:43
srry im new, need to get to know this platform better, thats why i closed this issue before

**Comment by qm13** [comment] 2021-11-01 16:57
@leGITplease It looks like you are using CUDA 11.5. Body Tracking v1.1 was tested on CUDA 11.1. Can you please downgrade to CUDA 11.1 and retest.

**Comment by ccddttsst** [comment] 2021-11-02 06:34
I have met exactly the same problem. CUDA11.1. Color, depth, and other streams work well. However, the k4abt_simple_3d_viewer crashed at opening without error message even with CPU mode. May I ask if you find any solution?

**Comment by lnocera** [comment] 2021-11-06 00:06
Similar issue on laptop and desktop with 2 different Azure Kinect:
- Followed all the steps including firmware update
- The Kinect Viewer works fine with color and depth
- The Kinect Body Tracking Viewer opens a blank window and shuts down with no error message (on Command Prompt)

**Comment by leGITplease** [comment] 2021-11-11 16:44
> 
> 
> @leGITplease It looks like you are using CUDA 11.5. Body Tracking v1.1 was tested on CUDA 11.1. Can you please downgrade to CUDA 11.1 and retest.

Im having some trouble with my pc currently due to installing an reinstalling certain applications(cuda and such) but one of these days im gonna test if it works, thanks.

edit: i am planning on reinstalling all on this system if the previousdoesnt work or would you think it is a good idea to use a virtual machine for instance or would that not work?

**Comment by cpkcpkcpk** [comment] 2021-11-21 00:53
Same problem here - The Kinect Viewer is working fine, but the Body Tracking Viewer quits instantly on launch with no error messages. It also crashes when launching in CPU mode from command line.

PC:
AMD Ryzen 5900x
NVidia 3080
32GB RAM
Windows 10 21H1 19043.1348

Tried with both CUDA 11.1 and 11.5.

**Comment by armonnaeini** [comment] 2021-11-22 03:05
Same problem, as well. Kinect Viewer works no problem, but I'm getting the same crash on launch problem as other users stated above.

NVIDIA RTX 3080
Intel i9
32GB RAM
Windows 11 Home 22000.318

**Comment by cpkcpkcpk** [comment] 2021-11-22 09:54
Just out of curiosity, is everyone having these issues using a Kinect from the new batch?

My old Kinect is out on loan so I can't test with that, but just got another as I saw they were finally back in stock.

**Comment by wangyangwang** [comment] 2021-11-22 16:27
having exact same issue here. followed all the steps. installed all c++ redist versions and both 11.1 and 11.5 cuda. nothing worked so far. 

windows 10 pro -  21h1 - 19041.1348

 intel (r) xeon(r) e-2286m 
nvidia geforce rtx 3060 ti

**Comment by atsukur** [comment] 2021-11-24 01:29
Same problem too. But I found workaround. Downgrading Nvidia driver.
I installed Nvidia Studio Driver 472.47. then it works fine.
<img width="416" alt="Screenshot 2021-11-24 102445" src="https://user-images.githubusercontent.com/69294861/143154465-612df24b-1d7c-4e85-89c6-622b21f34523.png">

maybe Nvidia driver issue?

**Comment by kondo1018008** [comment] 2021-11-24 09:00
I had the same problem, but downgrading the driver version to 472.12 solved the problem.
@atsukur Thank you so much
![スクリーンショット 2021-11-24 180016](https://user-images.githubusercontent.com/49856730/143206744-871ed15f-e895-403c-ba5f-258ed91c9033.png)
!

**Comment by wangyangwang** [comment] 2021-11-24 16:03
472 driver solved the issue for me too.

**Comment by leGITplease** [comment] 2021-12-03 11:36
Allright i got a couple things that could help the next person, thank you guys for trying to help to solve the problems with me! 

Even though i am not pinpoiting the problem, i can tell what solved it, my guess is driver/software incompatability:

I know this might not be the best or most efficient way but it works and might help out other people:

What i did in this exact order:

Reinstalled:

Windows 10 Pro (with a bootable usb)
windows updates
device drivers(motherboard)
nvidia drivers (the game ready version)
nvidia cuda 11.1
c++ noted in the documentation and in my first post in this topic
visual studio 2022, make sure you tag the boxes of the modules that apply to your situation such as kinect azure development
went to device manager and updated all the drivers for my usb ports

now the pc recognises the azure

then:

go to device manager and rightclick on ur screen adapter(gpu) and go back to the previous version of the driver(google it if u dont know exactly how)

azure sdk
azure body tracking

and.... it worked!

i made a recovery point for windows to instantly go back to this situation where the azure kinect works just to be safe so i can always go back there

Another tip that might help and occured to me while sitting almost asleep behind my pc(ill write it down so people who google this problem will find this): when the azure kinect white light is blinking there is no data connection as the documentation tells us. You might have switched the cables. The cables look the same, but make sure you havent switched up the cables: put the data connection into ur usb port of pc and the power connection into the power plug, which is logical but might be overlooked if u are thinking too hard :/

**Comment by CarlosBiscuit** [comment] 2022-01-30 11:54
Had the same issue with the Body Trackng Viewer crashing when trying to start. Followed @atsukur's advice and downgraded NIVIDA driver to version 472.47. After PC restart both the Azure Kinect Viewer and Body Tracking Viewer worked as normal again. I speculate that the driver got updated during a recent Windows Update session or something, because all my Azure Kinect apps were working fine two weeks ago (Jan 17th, 2022).

Anwyay, thanks, @atsukur!

**Comment by fkavache** [comment] 2022-02-25 20:00
I can confirm that in most cases the reason for k4abt_simple_3d_viewer crashing is the NVIDIA driver version.
NVIDIA drivers **after** version:

**472.12** for Game Ready drivers
and
**472.84** for Studio drivers

have some problems with OpenGL.

If anyone else has a similar problem please install above mentioned drivers.

**Comment by domportera** [comment] 2022-02-28 19:30
Can confirm - downgrading RTX 3080 driver down to 472.12 fixed this problem for us. Any plan to upgrade/maintain driver support?

**Comment by fractalfantasy** [comment] 2022-03-21 20:25
what if we have a newer graphics card like 3080ti that can't downgrade to 472.12?

**Comment by fkavache** [comment] 2022-04-07 08:56
Hi, @leGITplease @fractalfantasy @CarlosBiscuit could you please take a look at this thread?

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1763#issuecomment-1091234984

**Comment by qm13** [comment] 2022-05-25 01:18
Fixed in v1.1.2

**Closed as completed by qm13** 2022-05-25 01:18 UTC
Labels: Bug, Triage Approved, Body Tracking

**Comment by anggawahyuw** [comment] 2022-11-28 03:19
> Same problem too. But I found workaround. Downgrading Nvidia driver. I installed Nvidia Studio Driver 472.47. then it works fine. <img alt="Screenshot 2021-11-24 102445" width="416" src="https://user-images.githubusercontent.com/69294861/143154465-612df24b-1d7c-4e85-89c6-622b21f34523.png">
> 
> maybe Nvidia driver issue?

I can not install this driver because my laptop is not compatibel. RTX3070 Ti
