### ISSUE TITLE
Depth are interpolated at surface edge

### ISSUE THREAD

**Issue by YuHuangjie** [microsoft/Azure-Kinect-Sensor-SDK#789] opened 2019-09-24 08:21 UTC
**Describe the bug**

I notice that depth values at surface edges (depth discontinuities) are interpolated. This introduces wrong depth values and causes adhesion to another object. Examples are shown below. 

**Expected behavior**

I wonder if this is the correct behavior of the camera SDK. Is there an approach for getting non-interpolated depth maps?

**Screenshots**

I put a hand in front of me, leaving a 10 cm space. This depth map is undistorted following the given sample. I didn't use any OpenCV Linear interpolation.
![untitled](https://user-images.githubusercontent.com/22651124/65493440-6aab5080-dee5-11e9-9337-30c2379a3a03.png)

A closeup of my thumb is shown below. Clearly, depth values are interpolated along the edge. Note that I zoom in the image using 'nearest' method.
![untitled2](https://user-images.githubusercontent.com/22651124/65493661-de4d5d80-dee5-11e9-8c67-c6b55a91a5f3.png)

**Desktop:**
 - OS with Version: Windows 1803
 - SDK Version:  1.2.0
 - Firmware version:  1.6.102075014

**Comment by SergiiPatar** [comment] 2019-09-25 13:57
I have exactly the same issue. I compiled and tested the latest SDK (1.3.0-beta.0) and the problems remains.
I would be very nice to have a functionality to switch off the edge smoothing/interpolation

**Comment by rabbitdaxi** [comment] 2019-09-25 15:09
@YuHuangjie Thanks for the feedback. Based on your description, you are talking about the undistortion example, is that correct? The example is code samples to show the many ways of how to undistort the depth image. Depends on situation, 
- you can choose to use nearest neighbor if you want absolutely no interpolation at all.
- Or if you choose to use the bi-linear to achieve smoothness, agree that the depth discontinuity or the pixel between invalid/valid depth should be checked before interpolate. Please check this [commit](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/commit/82b850ba3c6c5fcebb3e74679896546029379dc5#diff-cf470fc175367392a1d65a6977f2231f) we added some threshold for the depth continuity check. If this cannot satisfy your purpose, please use the NN instead or propose a threshold for the depth discontinuity check.

**Comment by rabbitdaxi** [comment] 2019-09-25 15:10
@SergiiPatar is your issue also related to the undistortion example? or is your issue about the depth image straight from the SDK?

**Comment by YuHuangjie** [comment] 2019-09-26 02:25
@rabbitdaxi Thank you for your reply. The issue is not about undistortion. I tried removing undistortion completely and the problem still exists. So I think the issue is related to the depth map straight from the SDK.

**Comment by rabbitdaxi** [comment] 2019-09-26 17:08
@YuHuangjie If this is the depth map from the camera itself, this can be explained by the principle of time of flight and the depth algorithm. Two points:
- Signal can be received at the edge pixel mixing both foreground and background, for these pixels we often invalidate them, but it is possible when foreground and background is close, they were not invalidated and result in a pixel may have less accurate depth.  
- We do have filter in the depth engine, it is designed to keep depth discontinuity. But is also possible an explanation of what you see above.

**Comment by mbleyer** [comment] 2019-09-26 20:43
It might be an artefact of the filter. If two objects have similar depths, the filter might blur the depth discontinuity. Can you confirm that this blurring gets reduced when you move your hand further away from your body?

**Comment by bearpaw** [comment] 2019-10-03 22:40
Hi, I got the similar problem. From the visualization of the pointcloud, we can clearly see that the edge of the box is "blurred" with the desk surface as a "long tail". 

I guess it is caused by the interpolation/smoothness filtering within the depthengine? It would be very helpful if we can control the smoothness, as been done for the body tracking. 

    
![image (1)](https://user-images.githubusercontent.com/289501/66168906-72f54100-e5f3-11e9-87ba-1da755f288b3.png)
![image](https://user-images.githubusercontent.com/289501/66168907-72f54100-e5f3-11e9-9603-86e1279ceccb.png)

**Comment by YuHuangjie** [comment] 2019-10-08 04:03
@mbleyer If I move my hand further away, the blurring is reduced. In fact, boundary pixels are invalidated (black) in that case.

![Capture](https://user-images.githubusercontent.com/22651124/66366613-963d3900-e9c3-11e9-9cb9-acc10fe70022.PNG)

**Comment by catid** [comment] 2019-10-09 08:15
Is this issue present in both `K4A_DEPTH_MODE_NFOV_2X2BINNED` and `K4A_DEPTH_MODE_NFOV_UNBINNED`?

**Comment by bearpaw** [comment] 2019-10-10 16:43
> Is this issue present in both `K4A_DEPTH_MODE_NFOV_2X2BINNED` and `K4A_DEPTH_MODE_NFOV_UNBINNED`?

It happens to me for all four modes.

**Comment by mbleyer** [comment] 2019-10-10 23:51
Thanks for running the experiment. This seems to be an expected artefact of the smoothing filter used in the depth estimation software. Please note that changing the filter parameters is risky and might lead to very large depth errors (so-called dealiasing errors). We are therefore currently not planning to expose the filter parameters. I would recommend using a median filter on the depth map if these intermediate depth pixels represent a major issue.

**Comment by rabbitdaxi** [comment] 2019-10-14 17:38
This issue is expected with the current version of hardware and the software along with it. The filter is needed as a core part of the raw to depth process which already have parameters to help preserving the edges when there is large depth discontinuity. User can based on the specific scenario and environment data to apply further filtering either through customized thresholds or incorporate color image information. At this point, we close this issue as by design. You can also provide feedback on this [website](https://feedback.azure.com/forums/920053-azure-kinect-dk) for future product consideration.

**Comment by yipingp** [comment] 2019-11-11 12:31
> Hi, I got the similar problem. From the visualization of the pointcloud, we can clearly see that the edge of the box is "blurred" with the desk surface as a "long tail".
> 
> I guess it is caused by the interpolation/smoothness filtering within the depthengine? It would be very helpful if we can control the smoothness, as been done for the body tracking.
> 
> ![image (1)](https://user-images.githubusercontent.com/289501/66168906-72f54100-e5f3-11e9-87ba-1da755f288b3.png)
> ![image](https://user-images.githubusercontent.com/289501/66168907-72f54100-e5f3-11e9-9603-86e1279ceccb.png)

Hi, did you work it out or is there anything update? Thanks a lot!

**Comment by bearpaw** [comment] 2019-11-11 17:31
@yipingp unfortunately there is no luck on my side. Please let me know if you can figure something out. Thanks :)

**Comment by yipingp** [comment] 2019-11-12 01:45
@bearpaw Yes, sure

**Comment by mika-fischer** [comment] 2020-07-17 14:11
@yipingp @bearpaw Did you find a good workaround for this issue. I also experience it:
<img width="315" alt="2020-07-17_15h19_01_crop" src="https://user-images.githubusercontent.com/426158/87795050-d0d3dc00-c847-11ea-910d-9b1ccc949241.png">

This is a disc hovering over a flat surface. All the interpolated depth values are causing me a lot of headaches in segmentation...

**Comment by TacoDevelopment** [comment] 2021-02-19 18:17
@rabbitdaxi in my company we are facing similar issues. Is it possible to make this interpolation configurable/skippable?

**Comment by GaspardVCS** [comment] 2021-06-30 08:42
Hello, has anyone find a way to solve this issue? With my company we are trying to detect fruits. In this image, the yellow and red cloud points are supposed to be tomatoes but they don't have a round shape at all. Moreover, they are detected with a height of 30mm instead of 55...
The other objects are a tea box, a tea cup and a coke can. 
![Screenshot from 2021-06-29 17-02-18](https://user-images.githubusercontent.com/45163925/123930000-9a776a00-d98f-11eb-91f1-a570e602b71f.png)

**Comment by demul** [comment] 2021-09-06 02:32
Is there anyone solved this?
It will be very great if MS provide somethings like 'High Accuracy preset' in Intel Realsence SDK.
Azure have much better speculation than Intel Realsence's.
But Azure's poor SDK make many people to choose Intel Realsence.
It's obvious software gap.

**Comment by rabbitdaxi** [comment] 2021-09-06 06:26
@qm13 could you triage this issue with your team and see whether any improvements can be done? Likely it is due to how the current the current spatial filter works (seem mbleyer’s reply above) research and improvements are needed for the spatial filtering to address the issue.

**Closed** 2021-09-07 19:01 UTC
Labels: By Design

**Comment by TacoDevelopment** [comment] 2021-09-07 19:31
@qm13 could you elaborate on why this ticket is closed?
Is there maybe a different solution in progress?

**Comment by shabelson** [comment] 2022-05-19 22:49
Same issue here. During scanning  the camera creates trails between separate objects.
