### ISSUE TITLE
k4abt_simple_3d_viewer.exe can not be run in RTX3070 laptop graphc card

### ISSUE THREAD

**Issue by guobenyu1976** [microsoft/Azure-Kinect-Sensor-SDK#1508] opened 2021-02-16 12:39 UTC
I just bought a new asus air2 (RTX 3070 laptop graphic card) to replace the old thinkpad. The sdk, cuda, cudnn is new. 

1, Azure Kinect SDK(1.4.1) and viewer is ok. device is ok.
2, k4abt_simple_3d_viewer.exe can be run in cmd line as "k4abt_simple_3d_viewer.exe CPU"
3, device and k4abt_simple_3d_viewer.exe is ok in my old thinkpad

but, if i double click k4abt_simple_3d_viewer.exe in asus air2 notebook, the command window will appear, but picture window can not appear.

because it can be run in CPU mode, but can not be run in GPU mode.

**Comment by guobenyu1976** [comment] 2021-02-16 12:49
the system information is as below:
![software](https://user-images.githubusercontent.com/60568385/108065010-619dbf00-7098-11eb-930f-609d0745a226.jpg)

![hardware](https://user-images.githubusercontent.com/60568385/108064962-5185df80-7098-11eb-8dcb-f1bbd6995110.jpg)

**Comment by RoseFlunder** [comment] 2021-02-16 15:37
Known issue and according to Microsoft a patch comes soon:
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1481#issuecomment-763288112

**Comment by qm13** [comment] 2021-02-22 19:35
Duplicate of https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1481

**Closed as completed by qm13** 2021-02-22 19:35 UTC
Labels: Bug, Duplicate, Body Tracking

**Comment by guobenyu1976** [comment] 2021-03-03 06:28
Hi, qm13, when will the exe be updated?

when i met the problem, you said it is going to update in mid February.
So i wait the update and did other part of the project.
Now it is March. and the exe did not update yet.
the project has to solve it. We have to wait for the update or change the hardware.

May i know the planned date to update the exe?
if it is going to update this week or next week, i am going to wait for the update.
if it met some unexpected problem, it is hard to expect update in March. I am going to discuss with my boss, and change the hardware.

thanks very much!!


________________________________
发件人: qm13 <notifications@github.com>
发送时间: 2021年2月23日 3:36
收件人: microsoft/Azure-Kinect-Sensor-SDK <Azure-Kinect-Sensor-SDK@noreply.github.com>
抄送: guobenyu1976 <guobenyu@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/Azure-Kinect-Sensor-SDK] k4abt_simple_3d_viewer.exe can not be run in RTX3070 laptop graphc card (#1508)


Duplicate of #1481<https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1481>

―
