### ISSUE TITLE
Body orientation flip when leaning backward

### ISSUE THREAD

**Issue by cavisions** [microsoft/Azure-Kinect-Sensor-SDK#1074] opened 2020-02-13 12:55 UTC
**Describe the bug**

When leaning backward the body orientation is flipping as visible on the picture below. It changes its state several times per second. Even when body is not flipped the detection quality is less accurate as visible on the second picture. 

**To Reproduce**

This problem can be observed in the viewer application delivered with the body tracking SDK.

**Expected behavior**

**Screenshots**

![3D Visualization 2020-02-13 09-33-46](https://user-images.githubusercontent.com/15303035/74437122-ec395600-4e67-11ea-895d-0c4a00481931.jpg)
![3D Visualization 2020-02-13 09-33-46_1](https://user-images.githubusercontent.com/15303035/74437271-2571c600-4e68-11ea-87af-0c4535f18dd9.jpg)

**Desktop (please complete the following information):**
 - OS with Version: 1903
 - SDK Version:  1.3.0
-  Body Tracking SDK Version: 1.0
 - Firmware version:  1.6

**Comment by qm13** [comment] 2020-02-19 23:44
I have been unable to replicate this issue.

What mode are you running the depth sensor?
Can you try to replicate with different clothing?
Can you try to replicate in a different environment (point camera in different direction or move setup to different room)?

**Comment by qm13** [comment] 2020-03-11 23:39
Closing as duplicate of #575 
@Chrisbright10 do you have a recording which demonstrates the issue? If so please provide me a contact email address and I can provide details on how to share it with Microsoft.

**Closed by qm13** 2020-03-11 23:39 UTC
Labels: Body Tracking, Bug, Investigating
